-- MySQL Script generated by MySQL Workbench
-- 05/25/16 16:55:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`advert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`advert` (
  `idadvert` INT NOT NULL AUTO_INCREMENT,
  `price` MEDIUMINT(11) NULL,
  `address` VARCHAR(255) NULL,
  `agent` MEDIUMINT(11) NULL,
  `bedroom` SMALLINT(1) NULL,
  `livingroom` SMALLINT(1) NULL,
  `parking` SMALLINT(1) NULL,
  `kitchen` SMALLINT(1) NULL,
  `general_image` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `advertcol` VARCHAR(45) NULL,
  `location` VARCHAR(20) NULL,
  `hot` SMALLINT(1) NULL,
  `sold` SMALLINT(1) NULL,
  `type` VARCHAR(50) NULL,
  `recommend` SMALLINT(1) NULL,
  PRIMARY KEY (`idadvert`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscribe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscribe` (
  `idsubscribe` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NULL,
  `date_subscribe` DATE NULL,
  PRIMARY KEY (`idsubscribe`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
